# Generated by Django 2.1.5 on 2020-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'sub_category')},
        ),
    ]
